Shared/LobbyClient/Spring.cs, Springie/Springie/autohost/Polls/VoteForce.cs, Springie/Springie/spring/Spring.cs, Springie/Springie/spring/Talker.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#305
=> Revert "refix #300"

Springie/Springie/autohost/AutoHost_commands.cs
If comsharing modoption is enabled, Springie will make the teams comshared.
=> Springie comsharing

Shared/LobbyClient/Battle.cs, ZeroKLobby/MicroLobby/ExtrasTab/SkirmishControl.cs
this should fix http://zero-k.info/Forum/Thread/11318 
this bug effect people who PC's region is set to use comma as decimal points (going to Pull immediately due to simple changes)
=> ZKL: fix Startbox setting non-functional for some people

Zero-K.info/AppCode/HtmlHelperExtensions.cs, Zero-K.info/Views/Shared/UserDetail.cshtml, Zero-K.info/Views/Users/AdminUserDetail.cshtml
Redacts username (and forum avatar) wherever referenced in site outside of user page; hides user page from non-admins
=> Hide "deleted" accounts

ZeroKLobby/ActionHandler.cs, ZeroKLobby/MicroLobby/ChatTab.cs, ZeroKLobby/Notifications/NotifySection.cs, ZeroKLobby/Notifications/WarningBar.cs
please comment if you think the title could use better word
=> ZKL: tweak title for Warning bar (don't write "Warning" for every message).

Shared/PlasmaDownloader/EngineDownload.cs
My C# is rusty at best, this may not even compile?
=> Added support for multiple branches?

Shared/LobbyClient/TasClient.cs, ZeroKLobby/MicroLobby/ChatTab.cs
fix #297 
The code for offline PM did not handle case of multiple line
=> ZKL: fix offline PM can't sent multiple line, and fix issue #297

Zero-K.info/AppCode/HtmlHelperExtensions.cs
as per request from 
http://zero-k.info/Forum/Thread/11435
link goes to
http://zero-k.info/Forum/Thread/867
=> forum: donator star link to contib page

Zero-K.info/AppCode/HtmlHelperExtensions.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#396
=> Revert "forum: donator star link to contib page"

Zero-K.info/Views/Contributions/ContributionsIndex.cshtml
Licho TODO
add costs summary for 2014
update server details if changed
=> ZK-info - updated Contributions page - Licho TODO

Zero-K.info/App_Start/BundleConfig.cs, Zero-K.info/Global.asax.cs, Zero-K.info/Styles/style.css, Zero-K.info/Views/Shared/_SiteLayout.cshtml, Zero-K.info/Web.config, Zero-K.info/asp.net.csproj, Zero-K.info/packages.config
bundles could probably do with better grouping and naming, then was just a direct copy/paste from the View.
=> move js and css from SiteLayout to bundles, add System.Web.Optimization

Zero-K.info/ContentService.svc.cs
I have no idea if this works but it can't break any worse than what we currently have...
=> Fix campaign events with a hammer

Shared/PlasmaShared/Connection.cs, ZeroKLobby/MicroLobby/ExtrasTab/SkirmishControl.cs, ZeroKLobby/MicroLobby/TextWindow.cs
increase size, choose 10x 
some NULL check for error found accidentally
=> Zkl increase log size

Benchmarker/SpringRun.cs, Shared/LobbyClient/Spring.cs
=> only set OMP_WAIT_POLICY=ACTIVE if its not set

ZeroKLobby/MicroLobby/BattleChatControl.cs
=> ZKL: Fix missing text message when notification is used

ZeroKLobby/MicroLobby/BattleChatControl.cs
it effectively called AddLine() twice
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/72fd4dd05fe22cc3ca144e55de938a0880212e0b
=> BattleChatControl: Undo "Fix issue #445"

ZeroKLobby/MicroLobby/ChatBox.cs, ZeroKLobby/MicroLobby/ChatControl.cs
I added a small but useful new option in Right-click Contextmenu that tell ZKL to defocus all Chatlines except the clicked word or a playername.
Mechanism:
- What I added is a function which re-colour the Chatlines grey except the lines which contain the targeted term. It operate 100% like existing "Show join/leave lines" option.
The aim:
- To help user find message said by a person when the Chatlines is cluttered with message said by multiple people.
=> ZKL: add ChatLines defocus feature.

Shared/LobbyClient/Protocol/Messages.cs, ZkLobbyServer/LoginChecker.cs
This implements @cleanrock's proposal.
=> Include LobbyVersion in User message.

ZeroKLobby_NET4.0/Config.cs, ZeroKLobby_NET4.0/LobbyClient/Protocol/Messages.cs, ZeroKLobby_NET4.0/MicroLobby/ToolTabs.cs, ZeroKLobby_NET4.0/PlasmaShared/GlobalConst.cs, ZeroKLobby_NET4.0/Program.cs, ZeroKLobby_NET4.0/ZeroKLobby_NET4.0.csproj
re-enable autoupdate but set to target Zero-K_NET4.0 which don't exist (maybe exist in future?)
include changes from other ZK projects
=> ZklNET4: sync some changes

Zero-K.info/Controllers/GithubController.cs
- adds pull request notification
- adds repository identification
- probably doesn't work 
- i have no idea why [{0}] was formerly completely abjectly absent from the message
=> attempt to improve git notifications

Springie/Springie/autohost/AutoHost.cs, Springie/Springie/autohost/AutoHost_commands.cs, Springie/Springie/autohost/CommandList.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#518
=> Revert "obediation election deprecation notification"

Springie/Springie/autohost/AutoHost.cs, Springie/Springie/autohost/AutoHost_commands.cs, Springie/Springie/autohost/CommandList.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#523
=> Revert "Revert "obediation election deprecation notification""

Springie/Springie/autohost/AutoHost_commands.cs, Springie/Springie/autohost/CommandList.cs, Springie/Springie/autohost/Polls/VoteMove.cs
=> ![vote]move to passworded hosts forbidden

ZeroKLobby/MicroLobby/ExtrasTab/LocalReplay.cs, ZeroKLobby_NET4.0/MicroLobby/ExtrasTab/LocalReplay.cs
accidentally included the word " develop" when reading the name from demo file
=> Zkl & zklNet4: local replay "can't find dev engine fix"

Springie/Springie/autohost/AutoHost.cs, Springie/Springie/autohost/AutoHost_commands.cs, Springie/Springie/autohost/CommandList.cs
People should already know it's deprecated and this fixes boss-on-public-host hax.
=> Remove !voteboss fully

Springie/Springie/autohost/AutoHost.cs, Springie/Springie/autohost/CommandConfig.cs, Springie/Springie/autohost/CommandList.cs
Same as #555 but with fixed auto merge
=> Disallow spectators to use most !commands

Zero-K.info/Controllers/UsersController.cs, Zero-K.info/Views/Shared/UserDetail.cshtml, Zero-K.info/Views/Users/ReportLog.cshtml, Zero-K.info/asp.net.csproj
=> add a report log to site

Springie/Springie/autohost/AutoHost_commands.cs
=> !predict uses 1v1 elo for 1v1

Zero-K.info/Views/Users/ReportLog.cshtml
* newest reports on top
* shows time of report
* proper formatting for the text (newlines etc)
=> Improve report log

ZeroKLobby/MicroLobby/TextWindow.cs
added TryCatch for error in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/591
TryCatch added in 
ReturnWord() https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/592/files#diff-ca25e4961298cd8dd6caedec07652eaeR1353
and 
ReturnChar() https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/592/files#diff-ca25e4961298cd8dd6caedec07652eaeR1294
might look a bit messy because of the added whitespaces.
=> ZKL: quickfix crash reported by "google". Not proper fix

Zero-K.info/Views/Users/AdminUserDetail.cshtml
Helps identify malicious smurfs easier
=> Mark banned smurfs accounts on admin account page

ZkLobbyServer/Client.cs
This fixes negative player count in battle list.
=> Update spectator count when a spectator disconnects

Shared/LobbyClient/Battle.cs
For lua reimplementation of startboxes - see https://github.com/ZeroK-RTS/Zero-K/issues/544
=> Add startbox config to startscript as modoption

Shared/LobbyClient/Battle.cs, Shared/LobbyClient/Protocol/Messages.cs
=> Master into stable

Shared/LobbyClient/Battle.cs, Springie/Springie/autohost/AutoHost_commands.cs, Springie/Springie/autohost/CommandList.cs, Springie/Springie/autohost/Polls/VoteShuffleBox.cs
into: !shufflebox off|all|occupied
=> Springie: tweak !shufflebox toward Sprunk requirement

Shared/LobbyClient/Battle.cs, Springie/Springie/autohost/AutoHost_commands.cs, Springie/Springie/autohost/CommandList.cs, Springie/Springie/autohost/Polls/VoteShuffleBox.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#636
=> Revert "Springie: tweak !shufflebox toward Sprunk requirement"

Shared/LobbyClient/Battle.cs
=> Startbox patch

Springie/Springie/MainConfig.cs
local testing _cannot_ and _should not_ be done on live db!
=> remove wrong documentation

Springie/Springie/autohost/CommandList.cs, Springie/Springie/autohost/Polls/AbstractPoll.cs, Springie/Springie/autohost/Polls/VoteMap.cs, Springie/Springie/autohost/Polls/VoteMove.cs, Springie/Springie/autohost/Polls/VoteSplitPlayers.cs
Allow specs to vote on !votemove and !votesplitplayers
Allow specs to start and vote on !votemap
=> Springie voting

ZeroKLobby/Config.cs, ZeroKLobby/Program.cs
Fixes #654
Note: This PR is going directly into stable! (to avoid having to cherry pick around welcome_screen merge)
=> Clean ZKL cache on first run

Zero-K.info/Controllers/UsersController.cs
Currently it never knows whose ban it removes.
=> Fix ban removal message

NightWatch/Nightwatch.cs
This adds #ai and #weblobbydev to bridged channels. 
**BEWARE**: PR is to stable directly, because master is in WIP state.  
To be merged in dead hours.
=> Extend channel bridging to #ai and #weblobbydev

Zero-K.info/Views/Battles/Detail.cshtml, Zero-K.info/Views/Home/UserTooltip.cshtml, Zero-K.info/Views/Ladders/ladders.cshtml, Zero-K.info/Views/Shared/UserDetail.cshtml
Related to https://github.com/ZeroK-RTS/Zero-K/pull/910
=> Read award images from site instead of github

Springie/Springie/Main.cs, Springie/Springie/autohost/AutoHost.cs
=> fix springie spawn numbers

Zero-K.info/Views/Battles/Detail.cshtml, Zero-K.info/Views/Home/UserTooltip.cshtml, Zero-K.info/Views/Ladders/ladders.cshtml, Zero-K.info/Views/Shared/UserDetail.cshtml
URL construction is broken, see #695
=> Hardcode award URLs

Zero-K.info/Views/Battles/Detail.cshtml, Zero-K.info/Views/Home/UserTooltip.cshtml, Zero-K.info/Views/Ladders/ladders.cshtml, Zero-K.info/Views/Shared/UserDetail.cshtml
Reverts ZeroK-RTS/Zero-K-Infrastructure#696
=> Revert "Hardcode award URLs"

Springie/Springie/autohost/AutoHost_commands.cs
For manually balanced games !forcestart can be used
=> Springie: autobalance in custom rooms

Zero-K.info/MissionService.svc.cs, ZkData/MissionService/MissionUpdater.cs
=> fix mission service listing and updating on local test

ZkLobbyMultiplatformInstaller/packages/info.zerok.lobby.linux/meta/installscript.qs
=> Add support for opensuse in installer

ZkLobbyMultiplatformInstaller/packages/info.zerok.lobby.linux/meta/installscript.qs
=> Multiplatform installer: Add support for more distros

Springie/Springie/autohost/CommandList.cs
=> Springie: don't listen to !notify in chat channels

Springie/Springie/autohost/AutoHost.cs
Attempts to fix issue described in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/756#issuecomment-135983915
=> Springie: don't change map on room creation if it was already changed in past second

MissionEditor/CMissionLib/Actions/GUI/AddObjectiveAction.cs, MissionEditor/CMissionLib/Actions/GUI/AddPointToObjectiveAction.cs, MissionEditor/CMissionLib/Actions/GUI/AddUnitsToObjectiveAction.cs, MissionEditor/CMissionLib/Actions/GUI/ModifyObjectiveAction.cs, MissionEditor/CMissionLib/CMissionLib.csproj, MissionEditor/MissionEditor2/ListTemplates.xaml, MissionEditor/MissionEditor2/ListTemplates.xaml.cs, MissionEditor/MissionEditor2/MainWindow.xaml.cs, MissionEditor/MissionEditor2/MissionBase/LuaRules/Gadgets/mission_runner.lua, MissionEditor/MissionEditor2/MissionBase/LuaUI/Widgets/mission_gui.lua, Shared/LobbyClient/Spring.cs, Springie/Springie/autohost/CommandList.cs, Zero-K.info/Controllers/GithubController.cs, Zero-K.info/SpringieInterface/BattleResultHandler.cs, Zero-K.info/SpringieInterface/StartSetup.cs, ZeroKLobby/ChatToSpeech.cs, ZeroKLobby/MicroLobby/PlayerListBox.cs, ZeroKLobby/Steam/ZklSteamHandler.cs
Cherry picks some fixes from previous attempted deployment while skimming over anything that looks dangerous and refactory. 
Goes directly into stable, to be merged during dead hours.
=> Deploy cherries

Zero-K.info/Controllers/LaddersController.cs
Preventing inactive people from hogging the ladder promotes competition and activity.
=> Top50 ladder: require activity last week (was month)

Springie/Springie/autohost/AutoHost.cs, Springie/Springie/autohost/AutoHost_commands.cs, Springie/Springie/autohost/CommandList.cs, ZeroKLobby/ActionHandler.cs
=> Special rights handling for selecting map from website

Zero-K.info/ForumParser/Tags/TooltipTag.cs, Zero-K.info/asp.net.csproj
Shows a tooltip when mouse hovers over tagged text.
Example: [tooltip=Light Raider Bot]Glaive[/tooltip]
=> Forum: add [tooltip] tag

Zero-K.info/Views/Users/AdminUserDetail.cshtml
=> make adminuserdetails more readable

Shared/PlasmaShared/ISpringieService/AutohostMode.cs, Springie/Springie/Springie.csproj, Springie/Springie/app.config, Springie/Springie/autohost/Polls/VoteMap.cs, Springie/Springie/packages.config, Zero-K.info/SpringieInterface/Balancer.cs, Zero-K.info/SpringieInterface/MapPicker.cs
For things like Platinum and the new Unobtainium. Currently should be identical to teams host except blocks votes for special maps
[Rationale here](http://zero-k.info/Forum/Post/143065#143065)
=> Add Serious AutohostMode

Zero-K.info/Views/Maps/MapTags.cshtml
Just to clarify, this commit is untested and the picture a fake "that's how it's supposed to look like". Luckily there's http://test.zero-k.info/
=> Draw a "featured" tag on map's page

Zero-K.info/Views/Users/AdminUserDetail.cshtml
=> add quicklink for basic VPN / IP check to admin page

Springie/Springie/autohost/AutoHost.cs
=> Cherry-pick privilege escalation fix right into stable.

Zero-K.info/Styles/style.css
Oops! And that's why I shouldn't be doing a thousand cleanups with fixing buttons. I probably cut some of my copy-pasted code in half or whatever. Why didn't you warn me!
=> Missed code in previous commit

Shared/PlasmaShared/GlobalConst.cs, Zero-K.info/Controllers/MyController.cs
=> Comm names: max length 50 -> 20

Shared/LobbyClient/Protocol/Messages.cs, Shared/LobbyClient/TasClient.cs, Shared/LobbyClient/TasClient_structures.cs, Shared/LobbyClient/UserBattleStatus.cs, ZeroKLobby/Notifications/BattleBar.cs, ZkLobbyServer/ConnectedUser.cs
=> Implement startscript passwords.

Shared/LobbyClient/TasClient_structures.cs
This is needed to make #900 work properly.
=> Fix BattleUserEventArgs ctor to include script pw.

Zero-K.info/Views/Shared/DisplayTemplates/ForumPost.cshtml
people get confused, see http://zero-k.info/Forum/Thread/20694
=> make post collapse message clearer

Shared/LobbyClient/BotBattleStatus.cs, Zero-K.info/ContentService.svc.cs, Zero-K.info/Controllers/UsersController.cs, Zero-K.info/Views/Shared/UserDetail.cshtml
We're seeing bots sitting in rooms without the owner present. This should fix it.
=> Master -> stable to fix bot owner spoofing

Zero-K.info/Controllers/MapsController.cs
Some map tags could be changed by anyone through a forged html form
=> fix a map tagging exploit

Zero-K.info/Controllers/GithubController.cs
some clients consider whole string as url even with ) (
=> fixed brackets in github bot urls

Zero-K.info/Views/Shared/DisplayTemplates/ForumPost.cshtml
see http://zero-k.info/Forum/Thread/22275
=> Fixes moving vote buttons via forum posts

Shared/LobbyClient/Talker.cs
This is to solve https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1020
=> As spring has moved into UTF8, so shall ZKI. Made chat recognize UTF8 back and forth

Zero-K.info/ContentService.svc.cs, Zero-K.info/Controllers/HomeController.cs, ZkLobbyServer/ChannelManager.cs
There should probably be a way to share the query between all of them so such discrepancies won't happen in the future, in case there isn't an easy way to do so - here's a PR.
=> Conform top N players lists with the ladder

Zero-K.info/Styles/style.css
When using the "Link to this post" to create an url that contains an #anchor the post the anchor points to will be highlighted with a slightly dark teal background.
Example url: http://zero-k.info/Forum/Thread/14261?postID=159558#159558
=> Highlight posts that have been linked to.

ZeroKLobby/MicroLobby/BattleListControl.cs, ZeroKLobby/MicroLobby/HostDialog.cs
=> Master -> stable

Zero-K.info/Styles/style.css
[16:19:51]	&lt;ikinz&gt;	aeonios are you talking about the horrible lack of margins around rank icons on site?
=> margins for rank icons

Zero-K.info/AppCode/HtmlHelperExtensions.cs, ZeroKLobby/MicroLobby/Images.cs
fix #1205 
brackman will enjoy
=> google ranks

Shared/PlasmaShared/CommandJsonSerializer.cs
=> master->stable hotfix for chobby

ZkLobbyServer/autohost/CommandPoll.cs, ZkLobbyServer/autohost/Commands/BattleCommand.cs
Admins who are spec cannot vote and are not counted towards required votes to pass
Fixes #1283
=> Fix admin voting

ZkLobbyServer/ClientConnection.cs
See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1373#issuecomment-270851110
=> Case insensitive search for existing usernames during account registration

Zero-K.info/Views/Home/HomeIndex.cshtml
Yet another youtube thingie to improve retention. Don't want peoplers to start watching PA trailers accidentally.
=> Don't show related videos/suggestions after trailer

Zero-K.info/Views/Home/HomeIndex.cshtml
Makes it sound a little better IMO
=> proposed rewording of main page

Zero-K.info/Controllers/ClansController.cs, Zero-K.info/Views/Clans/Detail.cshtml
Don't accept external clanID, extract clanID from account
=> Refactor clankick

ZkLobbyServer/autohost/Commands/CmdEngine.cs, ZkLobbyServer/autohost/Commands/CmdForceGame.cs, ZkLobbyServer/autohost/Commands/CmdGame.cs
see cd10c7cee574e223a81747c8bbc2d3efc3af09fb - was passworded rooms previously -> arbitrary, thats what the room type is for
=> !game, !engine, !forceGame work on custom hosts only

Zero-K.info/Views/Ladders/ladders.cshtml, ZkData/Ef/WHR/IRatingSystem.cs, ZkData/Ef/WHR/WholeHistoryRating.cs
Ladders can now be updated live at no noticeable extra cost, as the rating system keeps a sorted tree of all ratings.
Should I put the List into the LadderModel? What's the advantage of having that?
=> ladder testing

Zero-K.info/Views/Ladders/ladders.cshtml
it was a visual character on ladder view, see http://i.imgur.com/gFMe3BB.png
=> remove forgotten closing ")"

Shared/PlasmaShared/GlobalConst.cs, Zero-K.info/Views/Shared/UserDetail.cshtml, ZkData/Ef/Account.cs, ZkData/Ef/WHR/PlayerRating.cs, ZkData/Ef/WHR/RatingSystems.cs, ZkData/Ef/WHR/WholeHistoryRating.cs, ZkLobbyServer/LoginChecker.cs, ZkLobbyServer/SpringieInterface/Balancer.cs, ZkLobbyServer/SpringieInterface/StartSetup.cs, ZkLobbyServer/autohost/Commands/CmdPredict.cs
=> [WHR] remove excessive debug

Zero-K.info/Views/Forum/PostList.cshtml
This reverts commit 9a7ec5008b83bb0a181204c030aed5a32e015fbe.
=> Revert "fix poll inside forum post not working properly"

Zero-K.info/Views/Poll/PollVoteList.cshtml
=> add whr to poll elo average

ZkLobbyServer/SpringieInterface/PlanetWarsMatchMaker.cs
This reverts commit 2413ef1e21d6ff37a7ec07f10d8ec649b969a7be.
=> Revert "balance same side also prevents militia play on same side"

Shared/LobbyClient/DedicatedServer.cs, Shared/LobbyClient/Talker.cs
Should be the right solution to the winning team handling.
Untested
=> Add SERVER_GAMEOVER parsing

Zero-K.info/Controllers/PlanetwarsController.cs
=> Better fleet capacity error message

AutoRegistrator/SteamDepotGenerator.cs, Fixer/Program.cs, MissionEditor/MissionEditor2/MissionBase/LuaUI/Widgets/mission_night.lua, Shared/PlasmaDownloader/Packages/PackageDownloader.cs, Shared/PlasmaShared/GlobalConst.cs, Zero-K.info/AppCode/Global.cs, Zero-K.info/Controllers/PlanetwarsController.cs, Zero-K.info/Views/My/CommanderProfile.cshtml, Zero-K.info/Views/Planetwars/Galaxy.cshtml, ZkData/Ef/Faction.cs
=> arbitrary master->stable to see if stuff explodes

Zero-K.info/ForumParser/Tags/GifvTag.cs, Zero-K.info/Styles/base.css
=> Stop gifv from going out of bounds

Shared/LobbyClient/Protocol/MatchMakerMessages.cs, Zero-K.info/Controllers/MapsController.cs, ZkLobbyServer/MatchMaker/MatchMaker.cs, ZkLobbyServer/ZkLobbyServer.cs
to fix #1747 
hope it doesn't change too much, just tried to keep it well readable.
=> Map tagging modification event for MatchMaker

ZkLobbyServer/MatchMaker/MatchMaker.cs
so people aren't thrown out of queues when featuring maps
=> keep queue references

ZkLobbyServer/autohost/CommandPoll.cs, ZkLobbyServer/autohost/Commands/BattleCommand.cs
see #1736 
This might have some unintended side effects.
=> Don't count AFK players for votes

Zero-K.info/Controllers/LobbyController.cs
Better wording suggestions welcome
=> Better instructions for replay/etc feature usage

ChobbyLauncher/Chobbyla.cs, Shared/PlasmaDownloader/Packages/PackageDownload.cs, Shared/PlasmaDownloader/PlasmaDownloader.cs
See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1781#issuecomment-320510101
Downloads from http://zk.repo.springrts.com/builds/. .sdz download will take place even if the corresponding rapid download is already present.
=> Chobby wrapper downloads latest ZK stable as .sdz

Zero-K.info/Controllers/UsersController.cs, Zero-K.info/Views/Users/AdminUserDetail.cshtml
This should streamline the rename process.
=> Allow admins to safely rename peoplers

Zero-K.info/Controllers/UsersController.cs
=> brutalize rename

ChobbyLauncher/ChobbyLoopbackMessages.cs, ChobbyLauncher/ChobbylaLocalListener.cs, Shared/PlasmaShared/Utils.cs
I'd like to help implement #1826 , how can I see loopback messages in Chobby for debugging?
=> Adding chobby wrapper download messages

Shared/PlasmaShared/GlobalConst.cs, Zero-K.info/AppCode/LadderCalculator.cs, Zero-K.info/Controllers/HomeController.cs, Zero-K.info/Views/Home/HomeIndex.cshtml, Zero-K.info/Views/Home/UserTooltip.cshtml, Zero-K.info/Views/Ladders/ladders.cshtml, Zero-K.info/Views/Shared/UserDetail.cshtml, ZkData/Ef/Account.cs, ZkData/Ef/WHR/IRatingSystem.cs, ZkData/Ef/WHR/WholeHistoryRating.cs, ZkLobbyServer/ChannelManager.cs, ZkLobbyServer/ITopPlayerProvider.cs
fix #1866
I've also removed a magic number that was duplicated in way too many places. Ladder size is now a constant.
=> WHR: always fill ladders with automayor

Zero-K.info/Views/Shared/UserDetail.cshtml
I don't know why I used ceil, but it throws the percentiles off by 0.1% and I can't stand that.
=> [Minor] Use rounding for percentile

ZkData/Ef/SpringBattle.cs, ZkData/Ef/WHR/RatingSystems.cs
=> Count unsupported maps for elo

ZkData/Ef/WHR/RatingSystems.cs, ZkData/Ef/WHR/WholeHistoryRating.cs
What do we still need to get this done?
=> test whr on live

Zero-K.info/AppCode/Global.cs
=> Give donators public exposure

Zero-K.info/Views/Shared/UserDetail.cshtml, ZkData/Ef/WHR/RatingSystems.cs
=> calculate whr 5 years back instead of 2

Shared/PlasmaShared/ISpringieService/BotTeam.cs, ZkLobbyServer/autohost/MapPicker.cs
http://zero-k.info/Forum/Thread/24622
=> try to select fitting maps in custom rooms

ChobbyLauncher/CrashReportHelper.cs, ChobbyLauncher/Program.cs
Detects Lua runtime errors (does not include OOM).
=> Crash reports: Lua runtime errors

ZkData/Ef/SpringBattle.cs
If this is what the people want, merge it.
=> Don't  count matchmaker for casual

ZkLobbyServer/MatchMaker/TourneyBattle.cs
=> use custom game mode for team tourney games

Zero-K.info/Controllers/ClansController.cs
fix #2129
@Licho1  does this have unintended side effects?
=> only delete clan polls on clan leave

Zero-K.info/Controllers/ChartsController.cs, Zero-K.info/Views/Charts/ChartsRatings.cshtml
Looks like this (Dante not included):
=> add more details to rating statistics page, add a description

ZkData/Ef/AccountRating.cs, ZkData/Ef/WHR/WholeHistoryRating.cs
Tested to work locally. Not sure if this is the intended solution though.
=> use db ratings for whr while initializing

ZkLobbyServer/MatchMaker/MatchMaker.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#2237
=> Revert "splitting queues and making things more readable"

Shared/LobbyClient/Protocol/MatchMakerMessages.cs, ZkLobbyServer/MatchMaker/MatchMaker.PlayerEntry.cs, ZkLobbyServer/MatchMaker/MatchMaker.ProposedBattle.cs, ZkLobbyServer/MatchMaker/MatchMaker.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#2291
=> Revert "make sure MM never invites to a battle that isn't actually possible"

Shared/LobbyClient/Protocol/Messages.cs, ZkLobbyServer/LoginChecker.cs, ZkLobbyServer/MatchMaker/MatchMakerBattle.cs
`MM 123: Coop`
`MM 456: Teams, avg skill 1337`
`MM 789: 1v1 Godde vs Randy, avg skill 2872`
=> Fix #2308, fancy MM room titles

ZkLobbyServer/ConnectedUser.cs, ZkLobbyServer/ServerBattle.cs, ZkLobbyServer/autohost/Commands/BattleCommand.cs, ZkLobbyServer/autohost/Commands/CmdAutohost.cs, ZkLobbyServer/autohost/Commands/CmdMap.cs, ZkLobbyServer/autohost/MapPicker.cs
=> Autohost fixes

Zero-K.info/Views/My/UnlockList.cshtml
All unlocks are for Kudos only at the moment. See #2407
=> Unlocks sticky bar: use Kudos amount

Zero-K.info/Views/My/Commanders.cshtml
Corrects the outdated link to the commander guide on the commander page.
=> Correct link to the commander guide on the commander page

Zero-K.info/ForumParser/Tags/AtSignTag.cs
No more untaggable people/clans
=> Add @f### @c### and @u### tagging to the forum

Shared/LobbyClient/DedicatedServer.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#2467
=> Revert "WIP"

Autoregistrator/Resources/campaignMaps.txt
Replaces Titan Duel 2.2 with Rogues River v1.2
See https://github.com/ZeroK-RTS/Chobby/commit/4428777ff349568ad6bb6b46051799905aea125d
=> Campaign map list update

Zero-K.info/Controllers/GithubController.cs, ZkLobbyServer/ZkLobbyServer.cs
Should work but coded blindly and untested.
=> WIP: Redirect crash reports to a "crashreports" channel

Shared/LobbyClient/Protocol/Messages.cs, ZkData/Ef/Resource.cs, ZkLobbyServer/ServerBattle.cs, ZkLobbyServer/autohost/CommandPoll.cs, ZkLobbyServer/autohost/Commands/CmdMap.cs
=> Display map size in map polls

ChobbyLauncher/ChobbylaLocalListener.cs
This reverts commit df6c334c5fb5e712b05e4eab6638b95599408e03.
=> Revert "fix logging bug"

Zero-K.info/Controllers/UsersController.cs, Zero-K.info/Views/Shared/DisplayTemplates/Punishment.cshtml
As per #2729 
- Actioning admin listed in #zkadmin
- Warnings do not read "PENALTY:"
- Messages are displayed to admins on user pages (users should find these in their PMs from Nightwatch)
=> Modaction interface improvements

Zero-K.info/Controllers/ForumController.cs, Zero-K.info/Views/Forum/NewPost.cshtml, Zero-K.info/Views/Forum/PostList.cshtml
Is showing the "Post comment" control both above and below the content intentional? I assume it is
=> Hide Post comment button when making/editing post

AutoRegistrator/SteamDepotGenerator.cs
Reverts ZeroK-RTS/Zero-K-Infrastructure#2753
=> Revert "Delete maps from Steam build before adding new maps"

Zero-K.info/Controllers/MapsController.cs, Zero-K.info/Views/Maps/Index.cshtml
I can't easily test this locally so somebody who actually understands infra should check this before pulling.
=> Added checkbox so users can tag uploaded maps as special.

Zero-K.info/Controllers/TourneyController.cs, Zero-K.info/Views/Tourney/TourneyIndex.cshtml
- Create, delete, and force multiple tourney rooms at once.
- Print replay list in forum-friendly format.
=> Batch tourney tools

ZkLobbyServer/ZkLobbyServer.csproj, ZkLobbyServer/autohost/Commands/CmdFlip.cs, ZkLobbyServer/autohost/Commands/CmdRoll.cs
This allows to support randomizing outcomes within a game for tournament support, this is likely a temporary solution until bot
support is available within a game lobby.
Addresses https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2805
=> Add CmdFlip and CmdRoll

ZkLobbyServer/ServerBattle.cs, ZkLobbyServer/autohost/Commands/BattleCommand.cs, ZkLobbyServer/autohost/Commands/CmdResign.cs, ZkLobbyServer/autohost/Commands/CmdStart.cs
I'm not super happy with this implementation (it's a bit ugly), but it's marginally better than what was there so it might be worth a pull request (it makes it easier to make limited changes to poll thresholds in the future). Feel free to reject it though, I'd prefer a broader refactor but can't justify the risk vs reward ratio.
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/9f659704e25239216b952876ba9858188e595f53 is based on forum comments (I personally have no stakes on large team games). I'm happy to take it out if making resign universally harder is considered a good change.
Addresses https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2808
=> Tweaks to vote margin requirement

ZkLobbyServer/ServerBattle.cs, ZkLobbyServer/autohost/Commands/BattleCommand.cs, ZkLobbyServer/autohost/Commands/CmdResign.cs, ZkLobbyServer/autohost/Commands/CmdStart.cs
For the resign threshold changes, should probably be merged during the night between Thursday and Friday so as to have it available for the weekend. Remember to check master builds first though because apparently they don't build.
=> (Check builds first) Stable for resign thresholds

ChobbyLauncher/ChobbylaLocalListener.cs
=> Launch Webpage in Mono Browser

SteamRoot/monoconfig
Fixes gui not showing in standalone while monoless
=> Kickstart - use local libgdiplus

Shared/LobbyClient/Battle.cs, Shared/LobbyClient/Protocol/Messages.cs, Shared/LobbyClient/ScriptGenerator.cs, Shared/PlasmaShared/ISpringieService/LobbyHostingContext.cs, Shared/PlasmaShared/MetaDataCache.cs, ZkLobbyServer/ConnectedUser.cs, ZkLobbyServer/MatchMaker/TourneyBattle.cs, ZkLobbyServer/ServerBattle.cs, ZkLobbyServer/ZkLobbyServer.csproj, ZkLobbyServer/autohost/Commands/CmdListMapOptions.cs, ZkLobbyServer/autohost/Commands/CmdListOptions.cs, ZkLobbyServer/autohost/Commands/CmdResetMapOptions.cs, ZkLobbyServer/autohost/Commands/CmdResetOptions.cs, ZkLobbyServer/autohost/Commands/CmdSetMapOptions.cs, ZkLobbyServer/autohost/Commands/CmdSetOptions.cs
* ZKLS added message SetMapOptions with Options property 
* ZKLS message JoinBattleSuccess: added MapOptions property
* ZKLS reset mapoptions on map change
* added chat commands !listmapoptions, !resetmapoptions and !setmapoptions
=> added support for mapoptions in zkls

Shared/LobbyClient/DedicatedServer.cs
=> Ingame kick also force-resigns

Zero-K.info/Controllers/ModsController.cs
Was updating when downloading the JSON metadata instead of when actually displaying the thread.
=> Fix #2791 (game mode forum threads)

Zero-K.info/Views/Battles/BattleDetail.cshtml
The one in the page title can't be copied.
=> Put battle ID on the battle ID page

ZkLobbyServer/SpringieInterface/StartSetup.cs
Lets you have events (e.g. Easter) based on time.
=> Modoptions: send current date
