ZeroKLobby/MicroLobby/BattleChatControl.cs
ZeroKLobby/MicroLobby/PlayerListBox.cs

fixed by adding the following pair:
int currentScroll = playerBox.TopIndex;
//add/remove Items
playerBox.TopIndex = currentScroll;

ZKL: tiny fix for scrollbar flickering (keep reset) each time player leave/enter battleroom

---

Zero-K.info/Views/Shared/UserDetail.cshtml

Non-standard Springie rights are not displayed for people who can change that themselves (because they can have any rights they want practically, and there is no standard rights value for them)

Springie rights display on profile

---

ZeroKLobby/Config.cs
ZeroKLobby/Controls/MinimapFuncBox.cs
ZeroKLobby/MicroLobby/SettingsTab.cs
ZeroKLobby/Program.cs
ZeroKLobby/ToolTips/PlayerTooltipRenderer.cs
ZeroKLobby/ToolTips/ToolTipHandler.cs
ZeroKLobby/Utils.cs

1) simply added option to disable tooltip for people who might not need tooltip. a workaround for #328 (fix #328 )
2) hard disabled Unitsync question box for Linux (because it cause hang there)
3) fix steam name tag cause their battleroom tooltip to cut off

ZKL: add option to disable tooltip for issue 328

---

Zero-K.info/App_Start/BundleConfig.cs
Zero-K.info/Global.asax.cs
Zero-K.info/Styles/base.css
Zero-K.info/Styles/menu.css
Zero-K.info/Styles/nicetitle.css
Zero-K.info/Styles/stars.css
Zero-K.info/Styles/style.css
Zero-K.info/Views/Shared/_SiteLayout.cshtml
Zero-K.info/Web.config
Zero-K.info/asp.net.csproj
Zero-K.info/packages.config

fixed 08f3957a1ce6f6de54b9a33faa7f57c3438f225b 
- tooltip styles now work properly (nicetitle.css was duplicated)
- updated all(?) images in css to absolute paths.
Only css missing from there is the ref to branding.css, since it doesn't appear to be used anywhere. If needed it can be readded to siteLayout outside of the bundle

fix tooltips, update image urls

---

Zero-K.info/Views/Battles/Detail.cshtml
Zero-K.info/Views/Home/UserTooltip.cshtml
Zero-K.info/Views/Ladders/ladders.cshtml
Zero-K.info/Views/Shared/UserDetail.cshtml

I'm not actually sure this will work as-is but it seems to when i hack the image src attribute in firebug and we have a test environment yay!
This is somewhat of a requirement for tourney award images but i guess i could svn commit them as well.

Use github as source for award images

---

ZeroKLobby/MicroLobby/ExtrasTab/SkirmishControl.cs
ZeroKLobby/MicroLobby/ExtrasTab/SkirmishControlTool.cs
ZeroKLobby/MicroLobby/ExtrasTab/TableReader.cs
ZeroKLobby/MicroLobby/PlayerListBox.cs
ZeroKLobby/MicroLobby/TextWindow.cs
ZeroKLobby/ZeroKLobby.csproj

This playerlist fix isn't related to  "refresh spam" or "can't right click" issue, its just other minor clicking/tooltip bug.
- if cursor move over empty space below the list of player, it won't always show tooltip of the last player in the list anymore 
Skirmish Tab:
- move my LUA table reader code into new file, trying to use it with other Form later.
- fix rapid clicking in Skirmisher playerlist not reliable/not-consistent/clumsy
- auto set Engine & Game to default version at first start

ZKL: small fix for Skirmisher and playerlist

---

ZeroKLobby/MicroLobby/PlayerListBox.cs
ZeroKLobby/MicroLobby/PlayerListItem.cs

REASON:
PlayerListBox's code didn't obey
https://msdn.microsoft.com/en-us/library/system.windows.forms.listbox.itemheight(v=vs.110).aspx
which says "ItemHeight" must return height of first item in the list when displaying multiple items with variable height (the "DrawOwnerVariable" tag).
Weirdly this omission didn't cause issue in NET (probably in NET the ListBox size is recalculated using value returned from "OnMeasureItem()").
FIX:
Override "ItemHeight" property and return the Height of the first item in the ListBox.
fix #441

ZKL PlayerListBox: fix issue # 441 (miscalculate playerlist size in MONO)

---

ZeroKLobby/MicroLobby/BattleChatControl.cs
ZeroKLobby/MicroLobby/ChatControl.Designer.cs
ZeroKLobby/MicroLobby/ChatControl.cs
ZeroKLobby/MicroLobby/PlayerListBox.cs

replace current MouseClick event with MouseUp/Down pair.
This is to address the following
1) PlayerList "HoverItem" require time to update properly after each MouseDown (or rapid click will cause clumsy behaviour). So MouseDown in BattleChatControl.cs is replaced with MouseDown/Up pair.
2) Right-click for MouseClick event don't exist in NET but exist in MONO. So replacing with MouseDown/Up make it consistent in both platform
Expected Benefit:
In effect user should perceive the clicking on playerlist to be more robust. Meaning: it always open Context-menu for correct username and work for both mouse button,

ZKL PlayerList: clicking behaviour tweak:

---

Springie/Springie/autohost/AutoHost.cs
Springie/Springie/autohost/Polls/VoteExit.cs
Springie/Springie/autohost/Polls/VoteResign.cs

Disconnected player can still communicate with Springie thru Spring. So, when Springie tries to get AFK status of exited player for vote, it crash because of "KeyNotFoundException"
(I saw this in springie log, from server). 
Fix https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/427

Springie: fix VoteResign & VoteExit crash Springie if player exited lobby

---

Springie/Springie/autohost/AutoHost.cs

I tested and it sound silly ingame (because its a personal message read by others)

Springie: undo adding message to tell player to reconnect to lobby

---

Zero-K.info/Controllers/MapsController.cs

Trying to access http://zero-k.info/Maps/JsonSearch results in an exception since the move to Entity Framework. As far as I'm aware, weblobby is the only user of JsonSearch and I prefer CORS to JSONP.

Fix Maps/JsonSearch and make it use CORS.

---

ZeroKLobby/MicroLobby/ToolTabs.cs

when we add a player as Friend (right/left+click on name - > Friend), the chat channel throw an error "KeyNotFoundException" because it tries to close and then re-open PM channel that might not exist yet.

zkl: some null check to fix Chat channel error

---

Springie/Springie/autohost/AutoHost_commands.cs

this should make setting modoption not sensitive to whitespace in between "=" and "," (in case player attempted to type it manually & didn't use ZKL to set options)
reported in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/500

Springie: ignore leading & trailing whitespace in key = value pair

---

Shared/PlasmaDownloader/PlasmaDownloader.cs
Springie/Springie/autohost/AutoHost.cs
Springie/Springie/autohost/AutoHost_commands.cs

Setengine normally occur when a global "SpringPaths" call a "SpringVersionChanged" event to all Autohost at same time. This work perfectly fine if we wanted to change engine for all Autohost at same time, but !setengine is coded to effect only a single Autohost. As result since "SpringVersionChanged" was called only once per !setengine, it won't get called again when commanded in other Autohost.
The fix is to tell each Autohost to use its own "SpringVersionChanged" event from local "SpringPaths" (already present in the code). This immediately fix https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/243
Have done some test.

Springie: fix buggy !setengine issue

---

ZeroKLobby/ToolTips/ToolTipHandler.cs
ZeroKLobby_NET4.0/ToolTips/ToolTipHandler.cs

because user32.dll not found exception in Linux Fedora
hopefully fix: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/521
I have uploaded zklNet4.0 version to server

Zkl & ZklNET4.0: won't use "tooltip Always on top" fix in Linux

---

ZeroKLobby/ActionHandler.cs
ZeroKLobby/NavigationControl.cs

Forget password when user logs out. Not doing that is a security issue because the password is stored in plain text and the user name can easily be recovered from the logs of the lobby and engine.

Forget password when user logs out.

---

ZeroKLobby/Program.cs

Ask if user wants desktop icon (some users may not want it). Also, do first run tasks only if this instance is the single instance alive. Otherwise, multiple instances may execute the first run tasks when started repeatedly in rapid succession.

Ask if user wants desktop icon and prevent potential race on first start

---

ZeroKLobby/Program.cs
ZeroKLobby/Utils.cs

should fix https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/529
Is caused by an engine check which always reset engine to default
The origin of bug: 
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/39e1de345d5e41e4f7052133441f45dc32f8cd5b , an irregular behaviour noted in #529 is due to it using "PackageDownloaded" event as delay, which is after ZKL finish downloading Rapid list from server at startup.

ZKL: fix intermittent default engine issue.

---

Shared/LobbyClient/Spring.cs

"X died in 123 seconds" uses ingame time now (same as duration).

Battle details page: show real time for dead message

---

Springie/Springie/autohost/Polls/VoteResign.cs

Using the afk status is a bad way of discounting people because it's unreliable.
For example Springie can force people to afk if they arent present when game is forced but they arent actually afk.
Or people who were really afk just came back.
Most important in 2v2 when one partner being falsely afk can make resign require only 1 vote ( see #395 ).
fixes #395
fixes #474

Voteresign: count afkers to success limit

---

ZeroKLobby/ZklResources.resx

I just switched <data name="away"... and <data name="away1"....'s files: away.bmp and away.png
For reference, both away files are located in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/tree/master/ZeroKLobby/Resources/PlayerStates
"away" is used by ZKL for the grey zZs displayed on afk users while "away1" is defined, but doesn't appear to be used for anything, see this search result:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/search?utf8=%E2%9C%93&q=away1
The .png version looks much better than the .bmp version and on top of that supports transparency. Here's an example picture I made with Paint that shows both the old and new away icons (see bottom right):
NOTE: This change is untested. I don't have any idea how2code zkl and just used the search options to find snippets of …

Use proper "away" icon by default (UNTESTED!)

---

ZeroKLobby/MicroLobby/BattleChatControl.cs
ZeroKLobby/MicroLobby/ChatControl.Designer.cs
ZeroKLobby/MicroLobby/ChatControl.cs
ZeroKLobby/MicroLobby/ExtrasTab/SkirmishControl.cs
ZeroKLobby/MicroLobby/PlayerListItem.cs

this fix https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/570
and fix it showing wrong result if you search (eg: in ZK channel) while you are in battleroom.
The bug was:
the 1st bug is because it wasn't intended to update while you search, but I don't see any regression of any function or feature while it does, so I made it obey https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/570 
Line https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/576/files#diff-3bb36f6c9dda362536527e8b698c38d1R445 
also, 2nd bug is because the player's SortOrder is also effected by player's team (for battleRoom), so I made it detect this case and skip them while searching
Line https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/576/files#diff-b5d6baab0eb4cbe29263bf07ee6a0a2cR250 …

Zkl: playerlist search fix/ improvement

---

Shared/PlasmaDownloader/Packages/PackageDownloader.cs
Shared/PlasmaDownloader/PlasmaDownloader.cs
Shared/PlasmaShared/GlobalConst.cs
ZeroKLobby/MicroLobby/DownloaderTab.cs

I remove the recent 3 sec anti-spam code from PackageDownloader.cs. This is because IMO its the caller that must avoid spam.
so I added 2 minute anti-spam code to PlasmaDownloader.cs (which is the caller of the Refresh). This period is same to one used by ZKL before ( as mentioned here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/558 )
Additional change is: 
- default engine to Spring 98.0.1-451
- add 20sec cooldown timer to Reload button in Rapid tab to avoid spam

Package downloader anti spam tweak

---

Springie/Springie/autohost/Polls/VoteResign.cs

Because there are way too many thrown games with the current 50% requirement.
Note that it's actually 67%+1 rounded down (provided thats how c# works), or:
2 people in 2v2
3 people in 3v3 and 4v4
4 people in 5v5
5 people in 6v6 and 7v7
etc.
Another option would be removing the vote's force-resign altogether (but keep the vote, it can help with communication), or only force-resigning !y voters.

Raises !y votes needed for !voteresign to 67%

---

Springie/Springie/autohost/AutoHost.cs
Springie/Springie/autohost/Polls/AbstractPoll.cs

* polls now start with !y vote from vote starter
* doing !command when not having rights for it but having rights for !votecommand will now run the vote variant, not the full variant (important because for example !move ignores room passwords, but !votemove doesnt).

Voting patch

---

Zero-K.info/Views/Home/UserTooltip.cshtml

* is problematic because it can take over half the screen in extreme cases (for example fireman)
* is no longer needed because you can't rename manually anymore

Site user tooltip: don't show aliases

---

ZkLobbyServer/Client.cs

This very likely fixes #511 (my theory of how it happened is a new player joins, doesn't get specced because there's no join check, then the other client sends UBS and gets specced).

Fix logic errors with maxPlayers

---

ZeroKLobby/NavigationControl.cs

Do not discard user name immediately on logout. Discarding the password should be enough.

Keep player name after logout for convenience

---

Springie/Springie/autohost/Polls/VoteResign.cs

Used to be 1/2+1 a month ago, but people always resigned "for no reason" (meaning too soon, either "to troll" or out of frustration from their comm dying, etc.). Is currently 2/3+1, but people complain because afkers have to vote. With afkers having to vote really being a bit of an issue I suggest 3/5+1.
Ultimately leavers and afkers should not be needed to vote, but from what (little) I understand that requires either a redo of "spring.StartContext" or a new BattleContext object to return always-up-to-date data **to prevent abuse of the voting system**. I'm not up to this task right now. See this commit for a nice summary of the issue: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/c961d1e9a281e9e6cf892d13cdb69db7d8d99aa6
Here's a table showing the number of votes required for …

Changes !voteresign threshold to 3/5+1

---

Springie/Springie/autohost/Polls/VoteResign.cs

With an exception not to allow a single person to resign the whole team (takes care of most pathological cases).

Voteresign: don't count afkers for threshold

---

Zero-K.info/Views/Planetwars/GalaxyOffline.cshtml

remove ultra-ugly poster and replace with info that PW is closed and that stuff on the page is recap of previous round

make pw page not uber bad

---

Shared/LobbyClient/Battle.cs
Springie/Springie/Springie.csproj
Springie/Springie/autohost/AutoHost.cs
Springie/Springie/autohost/AutoHost_commands.cs
Springie/Springie/autohost/CommandList.cs
Springie/Springie/autohost/Polls/VoteShuffleBox.cs

added (to Springie) a cousin of !start: !startshuffled which invisibly shuffle player's startbox, then start the game.
Is very lightweight and very easy to understand. Completely independent of games, shouldn't cause much issue.
Related: https://github.com/ZeroK-RTS/Zero-K/issues/544

xponen's startbox shuffler part 1

---

Springie/Springie/autohost/Polls/VoteMove.cs

Old title suggests all players get moved on successful vote which is confusing to some players.

More appropriate !votemove poll title.

---

Springie/Springie/autohost/AutoHost_commands.cs

Reverts ZeroK-RTS/Zero-K-Infrastructure#704
To apply this it should also happen in spring class where it contacts server for final balance.
But I don't think it's good idea, custom rooms are mainly for newbies. They don't know about force start.
Game should not do such things automagically, it should be explicity (balance button in lobby for example)

Revert "Springie: autobalance in custom rooms"

---

Shared/LobbyClient/Spring.cs

There are quite many unsaved replays, and quite many hardkill reports in springie log.
This is to see if 20s is enough for spring to quit. If it's not, going to check for dedicated hang ... somehow.

wait 20 seconds before hardkilling spring; see #743

---

Zero-K.info/Views/Battles/Index.cshtml
Zero-K.info/Views/Shared/UserDetail.cshtml

* Don't display user's name by default since it is not actually filtering by user name
* When following the user page's "last battles" links, do use the appropriate user name
Fixes #751

Fix replays index page

---

MissionEditor/CMissionLib/CMissionLib.csproj
MissionEditor/CMissionLib/Extensions.cs
MissionEditor/CMissionLib/Mission.cs
Shared/PlasmaDownloader/PlasmaDownloader.csproj
Shared/PlasmaDownloader/packages.config
Shared/PlasmaShared/PlasmaShared.csproj
Shared/PlasmaShared/packages.config
Tests/SharpCompressTests.cs
Tests/Tests.csproj
Tests/packages.config
ZkData/MissionService/MissionUpdater.cs
ZkData/ZkData.csproj

* Remove DotNetZip (incompatible MS-PL license); use System.IO.Compression built into .NET 4.5 instead (#257)
* Update SharpCompress 0.9.0 to 0.11.1

Zip handling patch

---

ZeroKLobby/ErrorHandling.cs

Back up and clear error log if it exceeds 50 MB (overwrite any existing backup)

Limit ZKL error log size

---

Zero-K.info/Views/Shared/UserDetail.cshtml

This commit is UNTESTED. I just randomly copied code without knowing C#, but expect this to work.
With this change users should see a "Contact administrators" button instead of the current "Report this player" button on their own profile page. That allows players to contact admins without "reporting" themselves. Note that this commit does not change the actual text that admins see in #zkadmin.
Reason for this commit:
#zkdev
[19:30]  Rafal[ZK] i think the "Report this player" button should change to "Contact moderators" when viewing own user page
[19:30]  Rafal[ZK] see #zkadmin why

"Report this player" -> "Contact admins" when reporting self

---

Zero-K.info/Views/Maps/Detail.cshtml

Tidal, mex cloud radius, wind -> ZK no longer uses these so displaying them just makes newbies confused.

Map page: don't show useless info

---

Zero-K.info/Views/Shared/UserDetail.cshtml

Fixes #220
This removes "Chat with xxx in the lobby" from user xxx's profile when the profile page is viewed by xxx. In other words, when I visit my own profile page (or zero-k.info) while logged in I wont see the link.
That thing:

Remove "chat with myself" link

---

Zero-K.info/Views/Maps/MapTileList.cshtml

This also means map tags will occasionally fill less lines and just makes better use of space in general. The reason this width used to be different for each map is the variable rating bar.

Fixes some minor maplist quirks.

---

Zero-K.info/Views/Maps/Detail.cshtml
Zero-K.info/Views/Maps/MapTags.cshtml

Revert "Draw a "featured" tag on map's page"
This reverts commit 6fad03a35d5eda865490d66ea26bad9095c86cd0.
Add "Featured" tag to detailed map page. This time the tag is not drawn next to all other tags (and thus drawn twice on the map list), but instead only added to the end of the map name on map-specific pages.

Proper featured map tags

---

Zero-K.info/Styles/menu.css

(to clarify: This change is aimed at the horizontal currently top most horizontal bar showing "HOME, PLAY, MEDIA, MANUAL, ..., DONATE" + sub-menus and also contains the search box. By "sub-menu" I mean the additional navigation links that are displayed on mouse-over.)
* Added padding around links and made sub-menu links take the sub-menu's full width to make navigating the menu feel much nicer.
* Made font of top-most links slightly larger (sub-menu links remain the same).
* Fixed tooltip for Donation link being too far right (position:absolute needed a parent that was not position:static).
* Made navbar link tooltips be drawn at about the same height as the link and removed 10% transparency.

Small menu/navigation bar overhaul

---

Zero-K.info/Styles/menu.css

Oops! Apparently order is important. "margin" overwrote "margin-top". Anyway, I renamed it to "margin-left" because we don't really care about the other ends. This should be a good way to show what really matters.

fixes menu/nav-bar link tooltip positions

---

Zero-K.info/Styles/menu.css

People can still have their browser set to have an extreme minimum font size like 40 and break it, but that can always happen. Some day there should also be a small change to the HTML part of the navbar table, but that's not critical.

fixes navbar for people with large default font

---

Zero-K.info/Styles/style.css

.textbutton changes:
Added font-size:medium; to stop browsers from overwriting <input> fontsizes
Merged paddings to padding:0.4em 1em; to be the same as input.ui-button in jquery-ui.css
Added vertical-align:middle; to make sure <span> (default vertical-align:baseline) properly lines up with all the other buttons
Cleanups that don't affect styles, semantics unchanged:
In line 169 (now 197), shortened margin: 4px 1px 4px 1px; to margin: 4px 1px;
In line 191 (now 190), shortened padding: 15px 0 15px 0; to padding: 15px 0;
(see "The padding property can have from one to four values." on http://www.w3schools.com/css/css_padding.asp for a short explanation)
Also removed some empty lines, blank spaces at the end of lines and changed all blank space indents (usually four, sometimes two and five …

CSS: .textbutton changes and small cleanups

---

Zero-K.info/Views/Home/HomeIndex.cshtml

The current version looks pretty weird and is hard to read on the near-black background. This change should ensure (new) visitors notice the Github symbol. Here's what the new image looks like: http://i.imgur.com/c1J59Dy.png
I took the new logo "GitHub-Mark-Light-32px.png" straight from https://github.com/logos

Replace "Social Media" logos with simpler/non-404 resources

---

Zero-K.info/Controllers/MyController.cs
Zero-K.info/Views/My/CommanderProfile.cshtml
Zero-K.info/Views/My/UnlockList.cshtml
Zero-K.info/Views/Shared/UnlockedTechnologies.cshtml
Zero-K.info/Views/Shared/UserDetail.cshtml

Modules with XpCost <= 0 and not kudos-exclusive are treated as unlocked (to maximum count) if player meets the required level.
(This is intended to facilitate making all current unlocks on site free for all players, now that dynamic comms are here)

Support for free unlocks

---

Springie/Springie/autohost/AutoHost_commands.cs

Extension of the kick time is undocumented. People with malicious intent who might have experience/knowledge about this concept are the most likely to circumvent it, while others only get needlessly confused and punished.

Do not extend !kick time upon rejoin attempt

---

Zero-K.info/Controllers/LaddersController.cs

I didn't test it locally, but I think it's minor enough to be probably correct :D
I wanted to check whether a game was actually ranked (then you could also check whether they're 1v1/team games), but I'm not sure if it's possible and how.

Don't consider a player active on the ladder if they only speced games lately

---

ZeroKLobby/MicroLobby/BattleIcon.cs
ZeroKLobby/MicroLobby/TextWindow.cs
ZeroKLobby/ToolTips/BattleTooltipRenderer.cs
ZeroKLobby/ToolTips/MapTooltipRenderer.cs
ZeroKLobby/ToolTips/PlayerTooltipRenderer.cs
ZeroKLobby/ToolTips/ToolTipHandler.cs

> Replace as many uses of graphics.MeasureString and graphics.drawString with TextRenderer.MeasureText and TextRenderer.DrawText as possible
Fixes #1108 
See http://stackoverflow.com/a/23230570 for more details
Side effect: Scrolling text window now has noticable delay, particularly when window height is large

ZKL: Replace GDI+ text functions where possible

---

Zero-K.info/Views/Shared/TopMenu.cshtml

Whitespace characters are illegal in URLs. I replace them with _ instead of + or %20 because the wiki pages themselves use _

Make guide urls in top navbar valid

---

Zero-K.info/Views/Shared/_SiteLayout.cshtml

HTML height attributes do not accept letters. "150px" would be valid in CSS, but not in HTML where it's px by default.
This change should stop the non-logo content of zero-k.info from jumping down while the page is being drawn by reserving space for the logo right from the start, even before the image completes loading.

Fix ZK logo height attribute

---

Zero-K.info/Views/Battles/BattleIndex.cshtml
Zero-K.info/Views/Missions/Index.cshtml
Zero-K.info/Views/Shared/SiteSearch.cshtml

Inputs of type image require an attribute for alternative text. This makes buttons usable when images are not loaded (eg. when disabling them to store bandwidth on mobile, or when the file gets lost for whatever reason).

Add alt text for search buttons

---

ZkData/Ef/SpringBattle.cs

When comparing different rating systems, it became evident that ZK's ELO would make more accurate predictions with K=64 
See http://zero-k.info/Forum/Thread/22898
As ELO values are "off" since the last change so now would probably be the best time for other changes as well.

Adjust ELO constant

---

MissionEditor/CMissionLib/UnitSyncLib/Mod.cs
MissionEditor/CMissionLib/UnitSyncLib/NativeMethods.cs
MissionEditor/CMissionLib/UnitSyncLib/UnitSync.cs
Shared/PlasmaShared/UnitSyncLib/NativeMethods.cs
Shared/PlasmaShared/UnitSyncLib/UnitSync.cs

Update ZK's unitsync classes to replace function calls that were removed in the Spring 103+ dev versions of unitsync.
NOTE: CMissionLib version was tested, but PlasmaShared one was not!

Unitsync updates for Spring 103.0+

---

ZkData/Ef/SpringBattle.cs

It was showing the casual elo changes on MM battle pages. If both elo changes are supposed to be displayed (for admins), player.EloChange needs to be replaced by a Dictionary with keys  for each elo type.

Show "correct" (competitive) elo changes on battle stats page

---

Zero-K.info/Styles/base.css

Before:
After:
This is caused by the default stylesheet which this change overrides.

Fix chrome levelprogress

---

ZkLobbyServer/SpringieInterface/StartSetup.cs

The key is currently ignored by ingame. However all other unitdefs use unitname as the key so it would allow some simplification.

PW ingame defs: use unitname as table key

---

Zero-K.info/Controllers/GithubController.cs

Discord has a thing that makes urls embedded in angle brackets ( `<` `>`) not embeddable, but still clickable like normal links.
Inflicting this upon Nightwatch's github notifications will make #zkdev@Discord much more readable.

angle-quote nightwatch github spam, prevents embed

---

ZkLobbyServer/SpringieInterface/Balancer.cs

when automagically adding AIs to an empty coop game, specs are counted as players.

don't add AIs to fight specs

---

Zero-K.info/Controllers/UsersController.cs

This is useful to give people official warnings. If the punishment has no effect they might miss it completely. Currently they only see the punishment reason if they go to their user page.

PM people when they get punished

---

ZkLobbyServer/LoginChecker.cs

Misspelled usernames keep leading to confusion because it is expected for usernames to be case insensitive.

consider ignoring username case on login

---

SteamRoot/setup-zerok.sh

Improves the Linux zero-k dependency installation by trying the default terminal and xterm to inform the user about the password prompt if zenity is not available.

In case zenity is not installed, try default terminal and xterm.

---

Shared/LobbyClient/Protocol/Messages.cs
ZkData/Ef/Account.cs

This should allow displaying rank information in the lobby. 
Instead of using rank names I'd suggest simply displaying the current and next rank icon.

add rank information to userprofile message

---

SteamRoot/Zero-K.sh

Leaves `setup-zerok.sh` untouched, so it can be run manually by people who want to do it themselves.

Install packages on first run

---

ZkLobbyServer/SpringieInterface/StartSetup.cs

To make sure numbers that end up ingame use dot instead of comma for the decimal separator (Czech stuff).

Safety for number formatting

---

ZkLobbyServer/MatchMaker/MatchMaker.PlayerEntry.cs

I think 60 seconds was just set for testing originally? I like the fast matching, but with our increasing steam activity I feel we could make use of better quality matches.

Increase MM maximum expansion time to 3 minutes

---

ZkLobbyServer/MatchMaker/MatchMaker.PlayerEntry.cs

this prevents parties from being split and being put with randoms. This is because many people asked for a way to have their party be the entire team.

make sure parties always make up the entire team.

---

Zero-K.info/Views/Users/ReportToAdmin.cshtml

* different text for contacting vs reporting
* emphasize (b+u) the need to provide evidence because so far 90% of new people's reports dont contain it

Improve report page

---

Shared/LobbyClient/Battle.cs
ZkLobbyServer/MatchMaker/MatchMakerBattle.cs
ZkLobbyServer/MatchMaker/PlanetWarsServerBattle.cs
ZkLobbyServer/MatchMaker/TourneyBattle.cs
ZkLobbyServer/SpringieInterface/StartSetup.cs

They were scattered all over the place. Some were missing so this patch also fixes that:
* tourney rooms lacked the speed caps.
* all other room types except tourney lacked mutelobby.

Future-proofing for competitive modoptions

---

ZkLobbyServer/SpringieInterface/Balancer.cs
ZkLobbyServer/SpringieInterface/PartitionBalance.cs
ZkLobbyServer/ZkLobbyServer.csproj

This opens up an interface to implement balance checking for proposed MM matches without overloading the server.
The balance algorithm now runs in O(2^(n/2)) compared to O(n!/(n/2)!^2).

Implemented fast balance algorithm for teams

---

Shared/LobbyClient/Battle.cs
ZkLobbyServer/ConnectedUser.cs
ZkLobbyServer/ServerBattle.cs
ZkLobbyServer/ZkLobbyServer.csproj
ZkLobbyServer/autohost/Commands/BattleCommand.cs
ZkLobbyServer/autohost/Commands/CmdAutohost.cs
ZkLobbyServer/autohost/Commands/CmdMap.cs
ZkLobbyServer/autohost/Commands/CmdMaxElo.cs
ZkLobbyServer/autohost/Commands/CmdMaxLevel.cs
ZkLobbyServer/autohost/Commands/CmdMaxPlayers.cs
ZkLobbyServer/autohost/Commands/CmdMinElo.cs
ZkLobbyServer/autohost/Commands/CmdMinLevel.cs
ZkLobbyServer/autohost/Commands/CmdMinMapSupportLevel.cs
ZkLobbyServer/autohost/Commands/CmdPassword.cs
ZkLobbyServer/autohost/Commands/CmdResetOptions.cs
ZkLobbyServer/autohost/Commands/CmdSetOptions.cs
ZkLobbyServer/autohost/Commands/CmdTitle.cs
ZkLobbyServer/autohost/Commands/CmdType.cs

Autohosts can be created by an admin by calling !autohost in an existing room.
Autohosts have a fixed title, player limit, password and modoptions.
Autohosts change the map to a random featured map after each battle.
Additionally they can be customized using five new commands:
!maxelo, !minelo, !maxlevel, !minlevel, !minmapsupportlevel

Added autohosts

---

ChobbyLauncher/Chobbyla.cs

Generates many false reports that we can't really do anything about.

User-killed spring does not count as crash

---

ZkLobbyServer/SpringieInterface/StartSetup.cs

Previously a player could only get 1 extra comm (for a total of 2)
which failed when the other team had more than 2N players.
Now people can get more than 1 extra commander. See #2409

Extra comms: handle N vs 2N+X case

---

Shared/LobbyClient/Protocol/Messages.cs
ZkLobbyServer/ServerBattle.cs
ZkLobbyServer/autohost/CommandPoll.cs
ZkLobbyServer/autohost/Commands/BattleCommand.cs
ZkLobbyServer/autohost/Commands/CmdEndvote.cs
ZkLobbyServer/autohost/Commands/CmdN.cs
ZkLobbyServer/autohost/Commands/CmdVote.cs
ZkLobbyServer/autohost/Commands/CmdY.cs

Polls now have multiple options instead of just Yes and No.

Option polls

---

ZkData/Ef/Clan.cs

Hi,
I've recently tried to create a clan with a Greek character as `shortcut`. Apparently it broke the clan detail page as this `shortcut` is used for a part of the clan background file name.
[Invalid clan page](https://zero-k.info/Clans/Detail/494)
This simple regex should fix the issue (#2344) , unless other characters are required.

More strict check for clan shortcut (Fix #2344)

---

Zero-K.info/Views/Battles/BattleDetail.cshtml

This has not worked since 2016. Current state of Springie does not just fail at saving the logs - it doesn't even [try](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/search?q=InfologPathFormat&unscoped_q=InfologPathFormat).

Remove infolog link from battle detail view

---

Zero-K.info/Views/Download/DownloadIndex.cshtml

Prevent download widget showing as a grey rectangle when page viewed over HTTPS, referenced in #2666

Fix Download Mixed Content Warning

---

Zero-K.info/Controllers/LobbyController.cs
Zero-K.info/Views/Lobby/LobbyChatHistory.cshtml

This makes it easier to see a conversation in context when chasing down reports.
In theory this would be better done by a mechanism like on the replay search page/rating display, which can accept an arbitrary number of entries. The code which does that would however have to be generalized to accept arbitrary strings (i.e. Discord usernames) rather than just ZK accounts.
Four users will be sufficient for most purposes, this functionality is not visible to end-users anyway and this was far less effort to code. Somebody can generalize it later if they are looking for something to do.

Up to four users at once searchable in admin chat history

---

AutoRegistrator/SteamDepotGenerator.cs

This is so maps and content doesn't keep adding up in the Steam build, leading to a continuously increasing steam package.

Delete maps from Steam build before adding new maps

---

ZkLobbyServer/SpringieInterface/StartSetup.cs

My use-case is that this lets the cheat-menu widget know it has to use `!hostsay /foo` instead of `/foo`.
Another one would be avoiding sending data via `SPRINGIE:FOO` if we know there is no lobbyserver to receive it (awards, modstats, etc).

Tell Spring games are ZKLS-hosted

---

Zero-K.info/Views/Maps/Detail.cshtml

The map view previously had a Last Battles link that links to the unfiltered Battle index,
but applying a map filter is more useful in this context. Addresses #2792

MapDetail links back to all battles for the given map

---

Zero-K.info/Controllers/MapBansController.cs

The check on the maximum map ban length on update was dropped after a refactor, this commit reapplies it. The map banner will
not apply bans past a maximum threshold (currently 75%) so inserting excess bans will not break matchmaker but would give the player a couple of extra bans.

Add sanity check on map ban insertion

---

ZkLobbyServer/ServerBattle.cs
ZkLobbyServer/autohost/CommandPoll.cs
ZkLobbyServer/autohost/Commands/CmdResign.cs

This change makes resign require unanimous approval for small team games (up to 4v4) and makes resign a little harder for large team games, but can be tweaked depending on the exact desired behavior.
Based on feedback in https://zero-k.info/Battles/Detail/1060977
I've sanity checked this to work for 1 and 2 players but haven't fully tested past that, I will do that once I have sign off (it should work fine, but arithmetic errors are embarrassing and testing with 4 accounts locally is a pain)

Require one extra vote for resign polls to pass

---

SteamRoot/Zero-K_linux64.sh

Most Linux installs are now using 256 color terminals. The launcher conflicts with this. Disables 256 color support at launch of script to fix or improve [Chobby#755](https://github.com/ZeroK-RTS/Chobby/issues/755#issuecomment-772746566) (may need to be ported to itch separately)

Improve support on distros using 256 color terminals

---

ChobbyLauncher/CrashReportHelper.cs

The user already consents by clicking the report/benchmark button in the lobby.

Fix #2832, no popup for bugreports/benchmarks

---

Shared/PlasmaDownloader/PlasmaDownloader.cs
Shared/PlasmaShared/Utils.cs

Fix for 'Could not create SSL/TLS secure channel' to springrts.com on Windows 7 and similar. Reference https://stackoverflow.com/questions/2859790

TLS 1.2 Update for Launcher

---

ZkLobbyServer/autohost/Commands/CmdKick.cs

Having the battle id for a kick should make it easier to identify the game where
the kick took place, the map is also provided as a backup and to identify patterns.
This was suggested by Bakuhatsu and I wanted to derust my local infra. I've done a simple sanity check locally.

Add battle information to kick log

---

ZkLobbyServer/MatchMaker/MatchMaker.cs

Unless this was explicitly left out for formatting reasons, fix the typo with a missing e in 'have'
And add a new line to be consistent with most other files in Infra.

Fix likely typo (Add an 'e')

---

ZkLobbyServer/ServerBattle.cs

Just the actual `!command` part is made case-insensitive, not any arguments (though many already are).

Springie !commands case insensitive

---

Zero-K.info/Controllers/BattlesController.cs

This uses the ID generated by engine at game start, which is available ingame,
as opposed to the regular ZKLS ID which is only available after battle is over.
This way a battle can be identified while it is being played,
for example to generate battle links in ingame reports automatically.

Website: add /Battles/EngineID/x view

---

Zero-K.info/Views/Forum/NewPost.cshtml

Doesn't apply to mediawiki and avatarwiki is discouraged.

Drop avatarwiki from the forum formatting link

---

ZkData/Ef/WHR/WholeHistoryRating.cs

This will prolong initialization time by around 7-8 minutes based on timings from a restart on 2022-09-01
It should alleviate issues caused by non converged ratings after restart.

Run additional WHR iterations on initialization

---

Shared/LobbyClient/ScriptGenerator.cs

Right now it says the IP:port of the server, like
> Connecting to: [12.34.56.78]:12345
This looks scary, apparently some streamers think it's their own IP that just got broadcast public. The patch changes it to room title, like
> Connecting to: Teams All Welcome
It only works on fresh engines but should be harmless otherwise. See https://github.com/beyond-all-reason/spring/pull/1282

Set the "connecting to: xyz" message on early engine load

---

ChobbyLauncher/CrashReportHelper.cs

Game reloads were previously detected by [f=-000001] that followed either the start of the file, or [f={non-negative value}]
This gave incorrect results for games that were exited during the pre-game stage, as they never got non-negative frame numbers.
This improves on #2979

Use [ReloadOrRestart] to detect game reloads, instead of frame number.

---

Zero-K.info/Controllers/GithubController.cs

To better delimit adjacent commits. Right now it looks like this, where the intuitive reading is for the "red" grouping to be a single commit. But in reality it's the unintuitive "green" grouping:
Discord doesn't have the `<hr>` tag so use strikethrough on spaces to get a horizontal line.

Push commit discord message: add horizontal lines

---

Zero-K.info/Controllers/TourneyController.cs

asp.net's default modelBinder converts empty strings to nulls, `DisplayFormat` Attribute prevents this

fix : Tourney Control modOptions ZeroK-RTS#2992

---

Shared/LobbyClient/DedicatedServer.cs

Will let ingame have a proper UI timer. See https://github.com/ZeroK-RTS/Zero-K/pull/5372

Send pregame timing events to ingame

---

ZkLobbyServer/ServerBattle.cs
ZkLobbyServer/autohost/Commands/CmdEngine.cs

Blind attempt to move players of the previous game to the back of the waiting list
